### PR TITLE
Feature/gihub issue 26 add include isoform

### PR DESCRIPTION
**Pull request by godotgildor**
This PR surfaces the `include_isoform` parameter to the `UniprotkbClient` class as described in the GitHub Issue 26:
https://github.com/multimeric/Unipressed/issues/26

### CODE REVIEW

**Comment by godotgildor** [comment]
Sounds good. Thanks for putting the library together!

**Comment by multimeric** [comment]
Okay, CI should be fixed now. Feel free to merge from master and try again.

**Comment by godotgildor** [comment]
Just merged latest from `master` into my branch. Thanks for the heads-up.

**Review by multimeric — APPROVED** [review]

**Comment by multimeric** [comment]
Okay, I've double checked that the default was already `True` so this shouldn't change anything for users. Code and tests look good. Thanks!

**Comment by multimeric** [comment]
Released in 1.2.0: https://multimeric.github.io/Unipressed/#120.

**Pull request merged**
